services:
  - type: web
    name: smartmind-info-center
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python build_index.py
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
